### PR TITLE
add template for phoenix framework

### PR DESCRIPTION
**Pull request by Vaysman**
Phoenix is a web framework for the Elixir programming language.

phoenix

Here is a button

<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2FVaysman%2Fidx-phoenix%2Ftree%2Fmaster">
  Open in IDX
</a>

### CODE REVIEW

**Comment by davideast** [comment]
This looks great! I'm getting an error when I boot it up myself. 

image

**Comment by Vaysman** [comment]
> Thank you so much for the PR @Vaysman. This looks great! I'm getting an error when I boot it up myself.
> 
> image

Phoenix is the name of one of the dependencies (actually, the main one), so it would be best to choose a different name for your project. Perhaps something like PhoenixApp would be suitable.

**Comment by rodydavis** [comment]
Thanks for the PR! Works for me, and there are other frameworks with the same naming issue.

LGTM 🚀

Screenshot 2024-10-28 at 4 16 28 PM

**Comment by Vaysman** [comment]
> Thanks for the PR! Works for me, and there are other frameworks with the same naming issue.

@rodydavis  Is there any way to check the workspace name at creation? For example, a regular expression. Then we can prevent this from happening and improve the user experience.

**Comment by rodydavis** [comment]
Yep there is a WS_NAME variable that you get! You could replace it in bash if you wanted

**Pull request merged**
